version: '3'
services:
  app:
    container_name: isdustinscarworking-build
    build:
      context: ./
    volumes:
      - .:/opt/isdustinscarworking
    ports:
      - "3000:3000" 
    command: ["yarn", "${NPM_TASK:-start}"]