version: '3'
services:
  app:
    container_name: isdustinscarworking-build
    build:
      context: ./
    volumes:
      - .:/app/
    ports:
      - "3000:3000" 
    working_dir: /app/
    command: ["/bin/ash", "-c", "rm -rf /app/node_modules && cp -R /opt/isdustinscarworking/node_modules /app/node_modules && yarn ${NPM_TASK:-start}"]